version: '3.8'

services:
  app: 
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=imgbest
      
volumes:
  mongo_data:
